          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"adsrvr.org",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"blendlabs.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"browser-intake-datadoghq.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"crsspxl.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"dvnfo.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"gaug.es",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"getdrip.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"glassboxcdn.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"iesnare.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"leadpages.io",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"lpages.co",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"pro-market.net",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"pub.network",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"quantcast.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"springserve.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"usercentrics.eu",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
          {
            "priority": "regular",
            "process": "any",
            "owner": "any",
            "remote-domains":"destination: domain userzoom.com",
            "ports": "any",
            "protocol": "any",
            "notes": "On Dec 13, 2024, Safari via com.apple.WebKit.Networking tried to establish a connection to addons.business. The request was allowed via connection alert.",
            "action": "deny",
            "direction": "any"
          },
